version: '3'
services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    tty: true
    restart: unless-stopped
    volumes:
    - ./:/var/www
    networks:
      - placetopaystore_network
  webserver:
    depends_on:
      - app
      - db
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    working_dir: /var/www
    tty: true
    restart: unless-stopped
    networks:
      - placetopaystore_network
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./:/var/www
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
    - dbdata:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: placetopaystore
    networks:
      - placetopaystore_network

networks:
  placetopaystore_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
